# Generated by Django 5.0.1 on 2024-01-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='room',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
